"""add saved-file_path

Revision ID: 7d13a8f36c03
Revises: 83c1b577957f
Create Date: 2026-08-06 06:21:57.728297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d13a8f36c03'
down_revision: Union[str, Sequence[str], None] = '83c1b577957f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('saved_file_path', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'saved_file_path')
    # ### end Alembic commands ###
