"""add analysis processing checkpoint

Revision ID: fc7467fb8d61
Revises: 0fd4b5e60840
Create Date: 2026-08-09 14:54:30.235691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7467fb8d61'
down_revision: Union[str, Sequence[str], None] = '0fd4b5e60840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('last_processed_line', sa.BigInteger(), nullable=False))
    op.add_column('analyses', sa.Column('processed_bytes', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'processed_bytes')
    op.drop_column('analyses', 'last_processed_line')
    # ### end Alembic commands ###
