"""add evidence fields

Revision ID: 1466d19bd2b0
Revises: fc7467fb8d61
Create Date: 2026-08-10 06:11:25.871585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1466d19bd2b0'
down_revision: Union[str, Sequence[str], None] = 'fc7467fb8d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('resolved_identity', sa.String(length=255), nullable=True))
    op.add_column('evidence', sa.Column('identity_match_type', sa.String(length=50), nullable=True))
    op.add_column('evidence', sa.Column('identity_strength', sa.Float(), nullable=True))
    op.create_index(op.f('ix_evidence_resolved_identity'), 'evidence', ['resolved_identity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_resolved_identity'), table_name='evidence')
    op.drop_column('evidence', 'identity_strength')
    op.drop_column('evidence', 'identity_match_type')
    op.drop_column('evidence', 'resolved_identity')
    # ### end Alembic commands ###
