"""add evidence unique constraint

Revision ID: 9ca196c91d66
Revises: 1466d19bd2b0
Create Date: 2026-08-10 07:39:51.003672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca196c91d66'
down_revision: Union[str, Sequence[str], None] = '1466d19bd2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_evidence_analysis_fingerprint_identity', 'evidence', ['analysis_id', 'fingerprint', 'trace_id', 'request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_evidence_analysis_fingerprint_identity', 'evidence', type_='unique')
    # ### end Alembic commands ###
