MEBIBYTE = 1024 * 1024
GIBIBYTE = 1024 * MEBIBYTE
INGESTION_RAW_BATCH_BYTES = 10 * MEBIBYTE
INGESTION_RAW_BATCH_ITEMS = 20000
EVIDENCE_TIMELINE_PAGE_SIZE = 10000
MAX_INVESTIGATION_UPLOAD_BYTES = GIBIBYTE
UPLOAD_COPY_CHUNK_BYTES = MEBIBYTE
ARTIFACT_DETECTION_SAMPLE_BYTES = 64 * 1024
FILE_READ_CHUNK_BYTES = 64 * 1024
MAX_DIAGNOSTIC_RECORD_BYTES = MEBIBYTE
JSON_STREAM_BUFFER_BYTES = 64 * 1024
MAX_FINGERPRINT_LENGTH = 255
MAX_REPRESENTATIVE_LINE_BYTES = 64 * 1024 - 1

MAX_DIAGNOSTIC_ARTIFACTS = 200
MAX_OCR_IMAGES_PER_INVESTIGATION = 20
MAX_OCR_IMAGE_BYTES = 20 * MEBIBYTE
MAX_OCR_IMAGE_PIXELS = 25_000_000

SIMPLE_LLM_MAX_EVIDENCE_RECORDS = 200
SIMPLE_LLM_MAX_CONTEXT_BYTES = 2 * MEBIBYTE

TEMPORAL_CANDIDATE_MAX_NEIGHBORS = 40

SIMPLE_FALLBACK_MAX_ARTIFACT_BYTES = 2 * MEBIBYTE
SIMPLE_FALLBACK_MAX_TEXT_BYTES = 64 * 1024
SIMPLE_FALLBACK_MAX_TOTAL_CONTEXT_BYTES = 256 * 1024

CORRELATED_MAX_EVIDENCE_RECORDS = 5000
CORRELATED_MAX_CONTEXT_BYTES = 20 * MEBIBYTE

BOUNDED_SELECTION_MAX_AGGREGATE_GROUPS = CORRELATED_MAX_EVIDENCE_RECORDS * 4

IDENTITY_FULL_PAIRWISE_MAX_GROUP_SIZE = 128
IDENTITY_CANDIDATE_MAX_NEIGHBORS = 32

SIMPLE_FRONTEND_MAX_EVIDENCE_RECORDS = 5000
SIMPLE_FRONTEND_MAX_CONTEXT_BYTES = 20 * MEBIBYTE

SOURCE_STORAGE_ROOT = "uploads/sources"
MAX_SOURCE_ARCHIVE_BYTES = 200 * MEBIBYTE
MAX_SOURCE_TOTAL_BYTES = 500 * MEBIBYTE
MAX_SOURCE_FILES = 20_000
MAX_SOURCE_CONTEXT_FILE_BYTES = 5 * MEBIBYTE

SOURCE_CONTEXT_CACHE_BYTES = 32 * MEBIBYTE
SOURCE_CONTEXT_LINES = 15
GITHUB_CLONE_TIMEOUT_SECONDS = 60

DIAGNOSTIC_ATTRIBUTES_MAX_BYTES = 2 * 1024

SOURCE_INDEX_PROCESS_CACHE_MAX_ENTRIES = 8

CORRELATED_GEMINI_CONTEXT_MAX_BYTES = 3 * MEBIBYTE
