"""Non-secret tuning values for diagnostic ingestion and evidence processing."""

MEBIBYTE = 1024 * 1024
GIBIBYTE = 1024 * MEBIBYTE

# Conservative starting points for the 2-vCPU / 8-GiB benchmark target.
INGESTION_RAW_BATCH_BYTES = 10 * MEBIBYTE
INGESTION_RAW_BATCH_ITEMS = 20_000
EVIDENCE_TIMELINE_PAGE_SIZE = 10_000

MAX_INVESTIGATION_UPLOAD_BYTES = GIBIBYTE
UPLOAD_COPY_CHUNK_BYTES = MEBIBYTE
ARTIFACT_DETECTION_SAMPLE_BYTES = 64 * 1024
FILE_READ_CHUNK_BYTES = 64 * 1024
MAX_DIAGNOSTIC_RECORD_BYTES = MEBIBYTE
JSON_STREAM_BUFFER_BYTES = 64 * 1024

MAX_FINGERPRINT_LENGTH = 255
MAX_REPRESENTATIVE_LINE_BYTES = 64 * 1024 - 1
